# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Msgs',
            new_name='Msg_inbox',
        ),
    ]
